export const actionModels = {
  irrigate_drip: {
    id: 'irrigate_drip',
    displayName: 'Drip Irrigation',
    description: 'Deliver low-volume water directly to the root zone.',
    categories: ['Irrigation'],
    parameterOrder: ['waterVolumeLiters', 'durationMinutes', 'flowRate'],
    parameters: {
      waterVolumeLiters: {
        key: 'waterVolumeLiters',
        label: 'Water Volume (L)',
        type: 'number',
        min: 0,
        step: 5,
        required: true,
      },
      durationMinutes: {
        key: 'durationMinutes',
        label: 'Duration (minutes)',
        type: 'number',
        min: 1,
        max: 480,
        step: 5,
        default: 60,
        required: true,
      },
      flowRate: {
        key: 'flowRate',
        label: 'Flow Rate (L/min)',
        type: 'number',
        min: 0,
        step: 0.1,
      },
    },
    requirements: {
      functions: [
        {
          id: 'followPath',
          label: 'Follow Path',
          params: [],
        },
        {
          id: 'setFlow',
          label: 'Set Flow Rate',
          params: ['flowRate'],
        },
        {
          id: 'dispenseWater',
          label: 'Dispense Water',
          params: ['waterVolumeLiters', 'durationMinutes'],
        },
      ],
    },
  },
  move_assembly: {
    id: 'move_assembly',
    displayName: 'Move Assembly',
    description: 'Relocate an assembly to another tile.',
    categories: ['Logistics'],
    parameterOrder: ['assemblyId', 'destinationTileId', 'travelMode'],
    parameters: {
      assemblyId: {
        key: 'assemblyId',
        label: 'Assembly',
        type: 'entity',
        entity: 'assembly',
        source: 'tileAssemblies',
        required: true,
      },
      destinationTileId: {
        key: 'destinationTileId',
        label: 'Destination Tile',
        type: 'text',
        placeholder: 'Row,Column or Tile ID',
        required: true,
      },
      travelMode: {
        key: 'travelMode',
        label: 'Travel Mode',
        type: 'select',
        default: 'ground',
        options: [
          { value: 'ground', label: 'Ground' },
          { value: 'airlift', label: 'Airlift' },
          { value: 'autonomous', label: 'Autonomous Convoy' },
        ],
        required: true,
      },
    },
    requirements: {
      functions: [
        {
          id: 'pickUpAssembly',
          label: 'Pick Up Assembly',
          params: ['assemblyId'],
        },
        {
          id: 'navigateToTile',
          label: 'Navigate To Tile',
          params: ['destinationTileId', 'travelMode'],
        },
        {
          id: 'placeAssembly',
          label: 'Place Assembly',
          params: ['assemblyId', 'destinationTileId'],
        },
      ],
    },
  },
  harvest_crop: {
    id: 'harvest_crop',
    displayName: 'Harvest Crop',
    description: 'Harvest yield from a selected crop population.',
    categories: ['Plants'],
    parameterOrder: [
      'targetPlantId',
      'harvestPercentage',
      'estimatedYieldKg',
      'equipmentId',
      'destinationStorageId',
    ],
    parameters: {
      targetPlantId: {
        key: 'targetPlantId',
        label: 'Target Plant',
        type: 'entity',
        entity: 'plant',
        source: 'tilePlants',
        required: true,
      },
      harvestPercentage: {
        key: 'harvestPercentage',
        label: 'Harvest %',
        type: 'number',
        min: 0,
        max: 100,
        step: 5,
        default: 100,
        required: true,
      },
      estimatedYieldKg: {
        key: 'estimatedYieldKg',
        label: 'Estimated Yield (kg)',
        type: 'number',
        min: 0,
        step: 1,
        default: 100,
      },
      equipmentId: {
        key: 'equipmentId',
        label: 'Equipment',
        type: 'entity',
        entity: 'assembly',
        source: 'tileAssemblies',
        required: true,
      },
      destinationStorageId: {
        key: 'destinationStorageId',
        label: 'Destination Storage',
        type: 'entity',
        entity: 'storage',
        source: 'tileStorage',
        required: true,
      },
    },
    requirements: {
      functions: [
        {
          id: 'diagnosePlant',
          label: 'Inspect Plant',
          params: ['targetPlantId'],
        },
        {
          id: 'operateHarvester',
          label: 'Harvest Crop',
          params: ['equipmentId', 'targetPlantId', 'harvestPercentage', 'estimatedYieldKg'],
        },
        {
          id: 'transferYield',
          label: 'Transfer Yield',
          params: ['destinationStorageId'],
        },
      ],
    },
  },
  collect_manure: {
    id: 'collect_manure',
    displayName: 'Collect Manure',
    description: 'Gather manure from animal enclosures and store it for processing.',
    categories: ['Animal Ops'],
    parameterOrder: [
      'sourceAnimalGroupId',
      'volumeCubicMeters',
      'equipmentId',
      'destinationStorageId',
    ],
    parameters: {
      sourceAnimalGroupId: {
        key: 'sourceAnimalGroupId',
        label: 'Animal Group',
        type: 'entity',
        entity: 'animalGroup',
        source: 'tileAnimals',
        required: true,
      },
      volumeCubicMeters: {
        key: 'volumeCubicMeters',
        label: 'Volume (m³)',
        type: 'number',
        min: 0,
        step: 0.1,
        required: true,
      },
      equipmentId: {
        key: 'equipmentId',
        label: 'Equipment',
        type: 'entity',
        entity: 'assembly',
        source: 'tileAssemblies',
      },
      destinationStorageId: {
        key: 'destinationStorageId',
        label: 'Destination Storage',
        type: 'entity',
        entity: 'storage',
        source: 'tileStorage',
        required: true,
      },
    },
    requirements: {
      functions: [
        {
          id: 'prepareAnimalArea',
          label: 'Prepare Animal Area',
          params: ['sourceAnimalGroupId'],
        },
        {
          id: 'loadMaterial',
          label: 'Load Material',
          params: ['volumeCubicMeters', 'equipmentId'],
        },
        {
          id: 'transportMaterial',
          label: 'Transport Material',
          params: ['destinationStorageId'],
        },
      ],
    },
  },
};
