export const measurementExpiration = {
  topography: {
    elevation: 182,
    slope: 182,
    aspect: 182,
    drainageIndex: 182,
    waterTable: 7,
  },
  soil: {
    ph: 30,
    ec: 30,
    salinity: 30,
    cec: 180,
    organicCarbon: 180,
    N: 7,
    NH4: 7,
    P: 7,
    K: 7,
    DON: 7,
    Cd: 182,
    Pb: 182,
    As: 182,
    water: 1,
    infiltrationRate: 90,
    bulkDensity: 180,
    penetrationResistance: 90,
    aggregateStability: 180,
    hydraulicConductivity: 180,
    soilTemperature: 1,
    microbialCFU_good: 7,
    microbialCFU_bad: 7,
    mycorrhizalColonization: 30,
    earthwormCount: 30,
  },
  resources: {
    water: 1,
    waste: 1,
    electricity: 1,
    feed: 1,
    fertilizer: 7,
  },
  plants: {
    health: 1,
    fruiting: { pollinated: 1 },
  },
  animals: {
    health: 1,
  },
  default: 30,
};
